config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

get '/login', to: 'sessions#new', as: 'login'
post '/login', to: 'sessions#create'
delete '/logout', to: 'sessions#destroy', as: 'logout'
patch '/appointments/:id/toggle', to: 'appointments#appointment_toggle', as: 'appointment_helper'

get '/support', to: "application#support", as: "support"

root 'application#welcome', as: "home"
get '/get_started', to: "application#get_started", as: "get_started"
resources :users
resources :dogs
resources :appointments
# patch '/appointments/:id/appt_set', to: "appointment#set_appt_user", as "set_user"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    has_many :skills
    belongs_to :dog
    belongs_to :user, optional: true

    validates :title,:category,:location,:price, presence: true
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_secure_password

    has_many :appointments
    has_many :users, through: :appointments

    validates :name, :breed, :age, :personality, :size, presence: true

end

app/models/skill.rb
class Skill < ApplicationRecord
    :belongs_to :appointment
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

    has_many :appointments
    has_many :dogs, through: :appointments

    validates :full_name, :age, :occupation, :location, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized #lock down this whole app
  skip_before_action :authorized, only: [:welcome, :support,:get_started]
  helper_method :current_user #i can call current_user from a view

  def current_user
    # User.find would throw an error if we cannot find the user
    if session[:user_id]
      User.find_by({ id: session[:user_id] })
    else
      Dog.find_by({ id: session[:dog_id] })
    end
  end

  def logged_in?
    # nil is falsey in ruby
    # a user instance is truthy
    !!current_user
  end

  def authorized
    redirect_to login_path unless logged_in?
  end

  def welcome
  end

  def get_started
  end

  def support
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    def index
        if params[:appt_search]
            @appointments = Appointment.where(title:  params[:appt_search])
        else
            @appointments = Appointment.all
        end
    end

    def new
      if current_user.class.model_name.name == "Dog"
        @appointment = Appointment.new
        @dogs = Dog.all
        render :new
      else
        flash[:appt_notice] = "You do not have access to create appointment"
        redirect_to appointments_path
      end
    end

    def show
        @appointment = Appointment.find(params[:id])
        @users = User.all
    end

    def create
        appointment = Appointment.create(appointment_params)
        if appointment.valid?
            redirect_to appointments_path
        else
            flash[:appt_errors] = appointment.errors.full_messages
            redirect_to new_appointment_path
        end

    end

    def edit
        @appointment = Appointment.find(params[:id])
        @dogs = Dog.all
    end

    def update
        appointment = Appointment.find(params[:id])
        appointment.update(appointment_params)
        if appointment.valid?
            redirect_to appointment_path(appointment)
        else
            flash[:appt_errors] = appointment.errors.full_messages
            redirect_to edit_appointment_path
        end
    end

    def destroy
      @appointment = Appointment.find(params[:id])
      if current_user[:id] == @appointment.dog_id
        @appointment.destroy
        redirect_to appointments_path
      else
        flash[:cant_delete] = "This dog can not delete this appointment"
        redirect_to appointment_path(@appointment.id)
      end
    end

    def appointment_toggle
      @appointment = Appointment.find(params[:id])
      @appointment.user_id = current_user[:id]
      @appointment.save
      redirect_to appointment_path(@appointment.id)
    end

    private
    def appointment_params
        params.require(:appointment).permit(:title,:category,:dog_id,:location,:price,:description,:user_id, :date)
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  skip_before_action :authorized, only: [:index,:new,:create]

  def index
    @dogs = Dog.all
  end

  def new
    @dog = Dog.new
  end

  def create
    dog = Dog.create(dog_param)
    if dog.valid?
        redirect_to login_path
    else
      flash[:dog_errors] = dog.errors.full_messages
        redirect_to new_dog_path
    end
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
    @dog.update(dog_param)
    if @dog.valid?
      redirect_to dog_path(@dog.id)
    else
      flash[:dog_errors] = dog.errors.full_messages
        redirect_to edit_dog_path
    end
  end

  def destroy
      @dog = Dog.find(params[:id])
      @dog.destroy
      redirect_to dogs_path
  end

  private

  def dog_param
    params.require(:dog).permit(:username, :password, :name, :gender, :breed, :color, :age, :personality, :size, :location)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized

  def new
    render :new
  end

  def create
    if params[:dog_or_user] == "User"
      @user = User.find_by(username: params[:username])
    else
      @doguser = Dog.find_by(username: params[:username])
    end

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      session[:dog_id] = nil
        redirect_to '/'
    elsif @doguser && @doguser.authenticate(params[:password])
      session[:dog_id] = @doguser.id
      session[:user_id] = nil
        redirect_to '/'
    else
      flash[:notice] = "Invalid Username or Password"
      redirect_to login_path
    end
  end

  def destroy
    session.delete(:user_id)
    session.delete(:dog_id)
    flash[:logout] = "Logged Out"
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:index,:new,:create]
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

     def create
       user = User.create(user_params)
        if user.valid?
          redirect_to login_path
        else
          flash[:user_errors] = user.errors.full_messages
          redirect_to new_user_path
        end
     end

    def show
       @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      @user.update(user_params)
      if @user.valid?
        redirect_to user_path(@user.id)
      else
        flash[:user_errors] = user.errors.full_messages
          redirect_to edit_user_path
      end
    end


    private
    def user_params
        params.require(:user).permit(:username, :password, :full_name, :bio, :occupation, :age, :location)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/get_started.erb
<div class="body2">
<div class="button1">
<%= button_to "Create User", new_user_path, :method => :get, class: "waves-effect waves-light btn-large blue-grey lighten-3" %>
</div>
<div class="button1">
<%= button_to "Create Dog", new_dog_path, :method => :get, class: "waves-effect waves-light btn-large blue-grey lighten-3"%>
</div>
</div>

app/views/application/support.erb
<nav>
    <div class="nav-wrapper blue-grey lighten-4">
      <a href="/" class="brand-logo">PAWLY</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li> <% if current_user %>
          <%= link_to 'Appointments', appointments_path, method: :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1" %>
        <% end %>
        </li>
        <li> <%= link_to "Dogs", dogs_path, :method => :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1"%> </li>
        <li> <%= link_to "Users", users_path, :method => :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1"%> </li>
        <li> <%= link_to "Home", home_path, :method => :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1"%> </li>
        <li><% if current_user %>
          <%= link_to 'Logout', logout_path, method: :delete, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1" %>
        <% end %>
        </li>
      </ul>
    </div>
  </nav>

<div class="jessy">
  <div class="row">
    <div class="col s3 offset-s3">
      <div class="card">
        <div class="card-image">
          <img src="/jessy.jpg" style="width:338px;height:338px;">
          <span class="card-title"></span>
        </div>
        <div class="card-content">
          <p>Name: Jessy Hu</p>
          <p>Occupation: Student</p>
          <p>School: Flatiron School</p>
          <p>Location: Queens, New York</p>
          <br>
          <p>HIREEEE ME!</p>

        </div>
        <div class="card-action">
          <a href="https://www.instagram.com/jsy.hu/">Jessy Hu</a>
        </div>
      </div>
    </div>

    <div class="col s3">
      <div class="card">
        <div class="card-image">
          <img src="/vicky.png" style="width:338px;height:338px;">
          <span class="card-title"></span>
        </div>
        <div class="card-content">
          <p>Name: Victoria Mei</p>
          <p>Occupation: Student</p>
          <p>School: Flatiron School</p>
          <p>Location: Brooklyn, New York</p>
          <br>
          <p>HIREEEE ME!</p>

        </div>
        <div class="card-action">
          <a href="https://www.instagram.com/vickysdailystandup/">Victoria Mei</a>
        </div>
      </div>
    </div>
</div>
</div>

<div class="team flow-text grey-text text-lighten-1">
  <h2>THE TEAM!</h2>
</div>

app/views/application/welcome.erb
<div class="home-page">

  <div class="Logo">
    <img src="/pawly.png" style="width:135px;height:135px;">
  </div>

      <div class="started_button">
          <% if current_user == nil %>
            <%= button_to "Get Started", get_started_path, :method => :get, class: "waves-effect waves-light btn blue-grey lighten-3"%>
          <% end %>
      </div>

      <div class="login_button">
          <% if current_user == nil %>
            <%= button_to "Log in", login_path, :method => :get, class: "waves-effect waves-light btn blue-grey lighten-3"%>
          <% end %>
      </div>

      <div class="dog_button">
          <%= button_to "Dogs", dogs_path, :method => :get, class: "waves-effect waves-light btn-flat transparent grey-text text-darken-1"%>
      </div>

      <div class="users_button">
          <%= button_to "Users", users_path, :method => :get, class: "waves-effect waves-hard btn-flat transparent grey-text text-darken-1"%>
      </div>

      <div class="support_button">
          <%= button_to "Support", support_path, :method => :get, class: "waves-effect waves-hard btn-flat transparent grey-text text-darken-1"%>
      </div>

      <div class="logo flow-text white-text text-darken-2">
        <h4>PAWLY</h4>
      </div>

      <div class="logout">
          <% if current_user %>
            <%= button_to 'Logout', logout_path, method: :delete, class: "waves-effect waves-light btn blue-grey lighten-3" %>
          <% end %>
      </div>

      <div class="appointments">
          <% if current_user %>
            <%= button_to 'Appointments', appointments_path, method: :get, class: "waves-effect waves-hard btn-flat transparent grey-text text-darken-1" %>
          <% end %>
      </div>

</div>

<!-- ################################################################ -->

<div class="home-page-background">

  <div class="background">

    <div class="Paragraph flow-text white-text text-darken-2">
      <h6>Join the growing community of dogs and extremely talented people!</h6>
    </div>

    <div class="started_button2">
      <%= button_to "Get Started", get_started_path, :method => :get, class: "waves-effect waves-light btn-small blue-grey lighten-3"%>
    </div>

  </div>
</div>

app/views/appointments/edit.erb
<h1>Edit Appointment</h>

<ol>
  <% if flash[:appt_errors] %>
    <% flash[:appt_errors].each do |error| %>
      <li> <%= error %> </li>
    <% end %>
  <% end %>
</ol>


<%= form_for @appointment do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :category %>
  <%= f.select :category, ['Excerise', 'Breeding', 'Training', 'Dog Sitting', 'Grooming']%><br>
  <%= f.label :location %>
  <%= f.text_field :location %><br>
  <%= f.label :price %>
  <%= f.number_field :price %><br>
  <%= f.label :description %>
  <%= f.text_area :description%><br> 
  <%= f.label :dog %>
  <%= f.collection_select(:dog_id, @dogs, :id, :name, prompt: true)%><br>
  <%= f.submit %><br>

<% end %>

app/views/appointments/index.erb
<nav>
    <div class="nav-wrapper blue-grey lighten-4">
      <a href="/" class="brand-logo">PAWLY</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li> <%= link_to "Dogs", dogs_path, :method => :get, class: "waves-effect waves-light btn-flat white grey-text text-darken-1"%></li>
        <li> <%= link_to "Users", users_path, :method => :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1"%> </li>
        <li> <%= link_to "Home", home_path, :method => :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1"%> </li>
          <li>  <% if current_user %>
                <%= link_to 'Logout', logout_path, method: :delete, class: "waves-effect waves-light btn-flat white grey-text text-darken-1" %>
                <% end %>
          <li>
    </div>
  </nav>

<nav>
    <div class="nav-wrapper blue-grey lighten-4">
  <%= form_tag appointments_path, method: "get" do %>
    <div class="input-field">
    <input id="search" type="search" required name="appt_search">
    <label class="label-icon" for="search"><i class="material-icons left">search</i></label>
    <i class="material-icons">close</i>

    </div>
  <% end %>
  <br>
  
  </div>
  </nav>

<div class="row">
  <% @appointments.each do |appointment| %>
  <div class="col s3">
    <div class="card">
      <div class="card-image">
        <img src="https://i.imgur.com/OPAR3PC.jpg" style="width:338px;height:338px;">
        <span class="card-title"></span>
      </div>
      <div class="card-content">
        <p>Title: <%= appointment.title %></p>
        <p>Category: <%= appointment.category %></p>
        <p>Dog: <%= appointment.dog.name %></p>
        <p>Location: <%= appointment.location %></p>
        <p>Price: <%= appointment.price %></p>
        <p>Date: <%= appointment.date %></p>
      </div>
      <div class="card-action">
        <a href="<%= appointment_path(appointment) %>"><%= appointment.title %></a>
      </div>
    </div>
  </div>
  <% end %>
  </div>

  <div class="container">
  <ol id = "errors">
   <%= flash[:appt_notice] %><br>
   </ol>

app/views/appointments/new.erb
<h1 class = "form_header grey-text">New Appointment</h1>


<div class="container input-field">
  <ol id = "errors">
  <% if flash[:appt_errors] %>
    <% flash[:appt_errors].each do |error| %>
      <li> <%= error %> </li>
    <% end %>
  <% end %>
  </ol>

  <%= form_for @appointment, html: {class:"form_input"} do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %><br>

  <%= f.label :category %>
  <%= f.select :category, ['Excerise', 'Breeding', 'Training', 'Dog Sitting', 'Grooming'],{},{:class => 'browser-default'} %><br>

  <%= f.label :location %>
  <%= f.text_field :location %><br>

  <%= f.label :price %>
  <%= f.number_field :price %><br>

  <%= f.label :description %>
  <%= f.text_area :description%><br>

  <%= f.label :dog %>
  <%= f.collection_select :dog_id, @dogs, :id, :name, {},{:class => 'browser-default'}%> <br>

  <%= f.label :date %>
  <%= f.text_field :date, data:{ provide:'datepicker'}%>

  <%= f.submit class: "waves-effect blue-grey lighten-3 btn" %>
  <% end %>
</div>

app/views/appointments/show.erb
<nav>
    <div class="nav-wrapper blue-grey lighten-4">
      <a href="/" class="brand-logo">PAWLY</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li> <%= link_to "Dogs", dogs_path, :method => :get, class: "waves-effect waves-light btn-flat white grey-text text-darken-1"%></li>
        <li> <%= link_to "Users", users_path, :method => :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1"%> </li>
        <li> <%= link_to "Home", home_path, :method => :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1"%> </li>
          <li>  <% if current_user %>
                <%= link_to 'Logout', logout_path, method: :delete, class: "waves-effect waves-light btn-flat white grey-text text-darken-1" %>
                <% end %>
          <li>
    </div>
  </nav>

<ul id = "errors">
<h4><%= flash[:cant_delete]  %></h4>
</ul>

  <div class="row">
    <div class="col s4 offset-s2">
      <div class="card">

      <div class="card-content">
        <p>Appointment Title: <%= @appointment.title %> </p>
        <%if @appointment.user %>
        <p>Taken By: <%= @appointment.user.full_name %></p>
        <%else %>
        <p>Ops! This appointment has not been taken yet!</p>
        <%end %>
        <p>Location: <%= @appointment.location %></p>
      </div>
     </div>
    </div>
  </div>

    <div class="dog-profile-pic">
    <img src="/dogingrass.jpg" style="width:500px;height:500px;">
    </div>

    <div class="appointment_make_button">
    <%  if current_user.class.model_name.name == "User" && @appointment.user_id == nil %>
    <%= button_to "Take Appointment", appointment_helper_path(@appointment.id), :method => :patch, class:"waves-effect waves-light btn-large blue-grey lighten-3" %>
    
    </div>

     <div class="delete_dog_button">
    <%= button_to "Delete", @appointment, :method => :delete, class: "waves-effect waves-light btn-large blue-grey lighten-3"%>
    </div>
<% end %>

app/views/dogs/_form.erb
<div class="container input-field">
    <ol id = "errors">
  <% if flash[:dog_errors] %>
    <% flash[:dog_errors].each do |error| %>
      <li> <%= error %> </li>
    <% end %>
  <% end %>
    </ol>

<%= form_for @dog, html: {class:"form_input"} do |f| %>

  <%= f.label :username%>
  <%= f.text_field :username%> <br>

  <%= f.label :password%>
  <%= f.text_field :password%> <br>

  <%= f.label :name %>
  <%= f.text_field :name %> <br>

  <%= f.label :breed %>
  <%= f.text_field :breed %> <br>

  <%= f.label :color %>
  <%= f.text_field :color %> <br>

  <%= f.label :age %>
  <%= f.number_field :age %> <br>

  <%= f.label :personality %>
  <%= f.text_field :personality %> <br>

  <%= f.label :location %>
  <%= f.text_field :location %> <br>

  <%= f.label :size %>
  <%= f.select :size, ['Small', 'Medium', 'Large'],{},{ :class => 'browser-default'}%> <br>

  <%= f.label :gender %>
  <%= f.select :gender, ['Male', 'Female', 'Other'],{},{ :class => 'browser-default' }%> <br>
   <%= f.submit class: "waves-effect blue-grey lighten-3 btn" %>

  <% end %>
  </div>

app/views/dogs/edit.erb
<h1 class = "form_header">edit dog profile</h1>

<%= render "form" %>

app/views/dogs/index.erb
<nav>
    <div class="nav-wrapper blue-grey lighten-4">
      <a href="/" class="brand-logo">PAWLY</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li> <% if current_user %>
          <%= link_to 'Appointments', appointments_path, method: :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1" %>
        <% end %>
        </li>
        <li> <%= link_to "Users", users_path, :method => :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1"%> </li>
        <li> <%= link_to "Home", home_path, :method => :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1"%> </li>
        <li><% if current_user %>
          <%= link_to 'Logout', logout_path, method: :delete, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1" %>
        <% end %>
        </li>
      </ul>
    </div>
  </nav>


  <div class="row">
    <% @dogs.each do |dog| %>
    <div class="col s3">
      <div class="card">
        <div class="card-image">
          <img src="https://i.imgur.com/OPAR3PC.jpg" style="width:338px;height:338px;">
          <span class="card-title"></span>
        </div>
        <div class="card-content">
          <p>Name: <%= dog.name %></p>
          <p>Gender: <%= dog.gender %></p>
          <p>Color: <%= dog.color %></p>
        </div>
        <div class="card-action">
          <a href="<%= dog_path(dog) %>"><%= dog.name %></a>
        </div>
      </div>
    </div>

<% end %>
</div>

app/views/dogs/new.erb
<h1 class = "form_header grey-text">New Dog Form</h1>

<%= render "form" %>

app/views/dogs/show.erb
<nav>
    <div class="nav-wrapper blue-grey lighten-4">
      <a href="/" class="brand-logo">PAWLY</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li> <%= link_to "Dogs", dogs_path, :method => :get, class: "waves-effect waves-light btn-flat white grey-text text-darken-1"%></li>
        <li> <%= link_to "Users", users_path, :method => :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1"%> </li>
        <li> <%= link_to "Home", home_path, :method => :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1"%> </li>
          <li>  <% if current_user %>
                <%= link_to 'Logout', logout_path, method: :delete, class: "waves-effect waves-light btn-flat white grey-text text-darken-1" %>
                <% end %>
          <li>
    </div>
  </nav>

  <div class="row">
    <div class="col s4 offset-s2">
      <div class="card">

        <div class="card-content">
          <p>Name: <%= @dog.name %> </p>
          <p>Breed: <%= @dog.breed %></p>
          <p>Gender: <%= @dog.gender %></p>
          <p>Color: <%= @dog.color %></p>
          <p>Personality: <%= @dog.personality %></p>
          <p>Location: <%= @dog.location %> </p>
          <p>Size: <%= @dog.size %> </p>
          <p>Age: <%= @dog.age %> </p>
        </div>
        <div class="card-action">
          <a href=""><%= @dog.name %></a>
        </div>
      </div>
    </div>

    <div class="dog-profile-pic">
    <img src="/dogingrass.jpg" style="width:500px;height:500px;">
    </div>


    <div class="edit_dog_button">
      <% if current_user.class.model_name.name == "Dog" && current_user.id == @dog.id %>
      <%= button_to "Edit", edit_dog_path(@dog.id), :method => :get, class: "waves-effect waves-light btn-large blue-grey lighten-3" %>
    <% end %>
    </div>

    <div class="delete_dog_button">
      <% if current_user.class.model_name.name == "Dog" && current_user.id == @dog.id %>
      <%= button_to "Delete", @dog, :method => :delete, class: "waves-effect waves-light btn-large blue-grey lighten-3"%>
    <% end %>
    </div>

    <div class="appointment_make_button">
      <% if current_user.class.model_name.name == "Dog" && current_user.id == @dog.id %>
      <%= button_to "Make a new Appointment", new_appointment_path, :method => :get,class: "waves-effect waves-light btn-large blue-grey lighten-3" %>
    <% end %>
    </div>

    <div class="dog_name">
      <h1><%= @dog.name %></h1>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <%= favicon_link_tag asset_path('dog.png') %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.erb
<nav>
    <div class="nav-wrapper blue-grey lighten-4">
      <a href="/" class="brand-logo">PAWLY</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li> <% if current_user %>
          <%= link_to 'Appointments', appointments_path, method: :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1" %>
        <% end %>
        </li>
        <li> <%= link_to "Dogs", dogs_path, :method => :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1"%> </li>
        <li> <%= link_to "Home", home_path, :method => :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1"%> </li>
        <li><% if current_user %>
          <%= link_to 'Logout', logout_path, method: :delete, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1" %>
        <% end %>
        </li>
      </ul>
    </div>
  </nav>


  <div class="row">
    <% @users.each do |user| %>
    <div class="col s3">
      <div class="card">
        <div class="card-image">
          <img src="https://i.imgur.com/Bm1gCyS.png" style="width:338px;height:338px;">
          <span class="card-title"></span>
        </div>
        <div class="card-content">
          <p>Name: <%= user.full_name %></p>
          <p>Age: <%= user.age %></p>
          <p>Location: <%= user.location %></p>
        </div>
        <div class="card-action">
          <a href="<%= user_path(user) %>"><%= user.full_name %></a>
        </div>
      </div>
    </div>

<% end %>
</div>

app/views/users/show.erb
<nav>
    <div class="nav-wrapper blue-grey lighten-4">
      <a href="/" class="brand-logo">PAWLY</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li> <%= link_to "Dogs", dogs_path, :method => :get, class: "waves-effect waves-light btn-flat white grey-text text-darken-1"%></li>
        <li> <%= link_to "Users", users_path, :method => :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1"%> </li>
        <li> <%= link_to "Home", home_path, :method => :get, class: "waves-effect waves-hard btn-flat white grey-text text-darken-1"%> </li>
          <li>  <% if current_user %>
                <%= link_to 'Logout', logout_path, method: :delete, class: "waves-effect waves-light btn-flat white grey-text text-darken-1" %>
                <% end %>
          <li>
    </div>
  </nav>

  <div class="row">
    <div class="col s4 offset-s2">
      <div class="card">

        <div class="card-content">
          <p>Name: <%= @user.full_name %> </p>
          <p>Age: <%= @user.age %></p>
          <p>Occupation: <%= @user.occupation %></p>
          <p>Location: <%= @user.location %></p>
          <p>Bio: <%= @user.bio %></p>
        </div>
        <div class="card-action">
          <a href=""><%= @user.full_name %></a>
        </div>
      </div>
    </div>

    <div class="dog-profile-pic">
    <img src="/blake.jpg" style="width:500px;height:500px;">
    </div>

    <div class="edit_user_button">
      <% if current_user.class.model_name.name == "User" && current_user.id == @user.id %>
      <%= button_to "Edit", edit_user_path(@user.id), :method => :get, class: "waves-effect waves-light btn-large blue-grey lighten-3" %>
    <% end %>
    </div>

    <div class="delete_user_button">
      <% if current_user.class.model_name.name == "User" && current_user.id == @user.id %>
      <%= button_to "Delete", @user, :method => :delete, class: "waves-effect waves-light btn-large blue-grey lighten-3" %>
    <% end %>
    </div>

    <div class="user_name">
      <h1><%= @user.full_name %></h1>
    </div>